name: Cargo Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      XMPP_SERVER: ${{ secrets.XMPP_SERVER }}
      XMPP_USERNAME: ${{ secrets.XMPP_USERNAME }}
      XMPP_PASSWORD: ${{ secrets.XMPP_PASSWORD }}
      XMPP_USERNAME_B: ${{ secrets.XMPP_USERNAME_B }}
      XMPP_PASSWORD_B: ${{ secrets.XMPP_PASSWORD_B }}
    steps:
      - uses: actions/checkout@v4
      - name: Build binaries
        shell: bash
        run: cargo build
      - name: Check bundle publication
        shell: bash
        run: ./scripts/grep_bundle_publication.sh
