name: Cargo Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build binaries
        run: cargo build
      - name: Check bundle publication
        run: ./scripts/grep_bundle_publication.sh
